# -*- coding: utf-8 -*-
"""ekf_step3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJRfQLXtHIrZ5g65m0v4hZlkXVUPbzQ3
"""

import numpy as np
import matplotlib.pyplot as plt
import time

np.random.seed(42)

# =============================================================
# ELE8101 Estimation Theory - Group Coursework
# Step 3: Full 2D EKF on curved track with lateral dynamics
#
# State vector: x_t = [s_t, ell_t, v_s_t, v_ell_t]
#   s_t   : arc-length along track centreline (m)
#   ell_t : lateral offset from centreline, ell in [-2, 2] m
#   v_s_t : longitudinal velocity (m/s), prior: ~10 m/s, max 25 m/s
#   v_ell_t: lateral velocity (m/s), constrained to <= 0.55 m/s
#
# System model follows the Gauss-Markov structure from lectures:
#   x_{t+1} = A x_t + G w_t,   w_t ~ N(0, Q)
#   y_t     = h(x_t) + v_t,    v_t ~ N(0, R)
#
# Note: the measurement equation is nonlinear (range to beacons),
# so we use the EKF with a numerical Jacobian to linearise h(x_t)
# around the current estimate x_{t|t}.
# =============================================================

# --- Sampling parameters ---
# Beacons operate at 100 Hz => h = 0.01 s (from problem statement)
h = 0.01

# --- Track geometry (from problem statement: R=50, r=46, rho=20, d=100) ---
d   = 100.0
rho = 20.0
L   = 2*d + 2*np.pi*rho   # total track length ~325.7 m


def s_to_xy(s):
    """
    Map arc-length s to Cartesian coordinates (x, y) on the track centreline.
    The track has four segments (clockwise from top-left):
      Segment 1: top straight,    s in [0, d)
      Segment 2: right semicircle, s in [d, d + pi*rho)
      Segment 3: bottom straight,  s in [d + pi*rho, 2d + pi*rho)
      Segment 4: left semicircle,  s in [2d + pi*rho, L)
    Centreline radius used for arc segments is rho = 20 m (midpoint of 4 m lane).
    """
    s = s % L
    if s < d:
        return s, rho
    elif s < d + np.pi * rho:
        theta = (s - d) / rho
        return d + rho * np.sin(theta), rho * np.cos(theta)
    elif s < 2*d + np.pi * rho:
        return 2*d + np.pi*rho - s, -rho
    else:
        theta = (s - (2*d + np.pi*rho)) / rho
        return -rho * np.sin(theta), -rho * np.cos(theta)


def s_to_normal(s):
    """
    Unit normal vector to the centreline at arc-length s (pointing outward).
    Used to convert lateral offset ell into a Cartesian displacement.
    """
    s = s % L
    if s < d:
        return 0.0, 1.0
    elif s < d + np.pi * rho:
        theta = (s - d) / rho
        return -np.cos(theta), np.sin(theta)
    elif s < 2*d + np.pi * rho:
        return 0.0, -1.0
    else:
        theta = (s - (2*d + np.pi*rho)) / rho
        return np.cos(theta), -np.sin(theta)


def state_to_xy(x):
    """Convert state [s, ell, v_s, v_ell] to Cartesian (px, py)."""
    s, ell = x[0], x[1]
    cx, cy = s_to_xy(s)
    nx, ny = s_to_normal(s)
    return cx + ell * nx, cy + ell * ny


# --- State transition matrix A ---
# Longitudinal: s_{t+1} = s_t + h*v_s  (Euler integration)
# Lateral:      ell_{t+1} = ell_t + h*v_ell
# Long. vel:    v_s_{t+1}  = v_s_t + w_s   (random walk; speed fluctuates)
# Lat. vel:     v_ell_{t+1} = phi * v_ell_t + w_ell  (AR(1) damping)
#
# Motivation for AR(1) lateral model:
# The problem statement says the vehicle "tends to be close to the centre
# of the lane", so lateral velocity should be mean-reverting rather than
# a pure random walk (which would cause the vehicle to drift out of bounds
# as noted in Section 4 of the coursework brief).
# phi < 1 ensures the lateral velocity process is stationary (stable AR(1)).
# Value phi = 0.9 is a first guess; ideally this should be tuned against
# real data or a more principled vehicle dynamics model.

phi = 0.9   # TODO: justify this value more carefully in the report

A = np.array([
    [1, 0, h,   0  ],
    [0, 1, 0,   h  ],
    [0, 0, 1,   0  ],
    [0, 0, 0, phi  ]
])

# Noise input matrix G: process noise enters through velocity states only
G = np.array([
    [0, 0],
    [0, 0],
    [1, 0],
    [0, 1]
])

# --- Process noise covariance Q = diag(q_s, q_ell) ---
# w_t ~ N(0, Q) as in the Gauss-Markov model (lectures, Week 3)
# q_s   = 0.5  : longitudinal speed variance per step — vehicle speed
#                fluctuates around 10 m/s (problem statement)
# q_ell = 0.02 : small lateral noise — lateral motion is smooth
# Note: Q is not given in the problem; these are modelling assumptions
# that should be validated against simulation behaviour.
# A more systematic approach (e.g., EM-based Q estimation) is left for
# future work.
Q_mat = np.diag([0.5, 0.02])

# --- Measurement noise variance R ---
# Problem statement gives sigma_v = 1.5 m (std dev of beacon ranging error).
# No PDF is specified, so we assume Gaussian: v_t ~ N(0, R), R = sigma_v^2.
R_var = 1.5 ** 2

# --- Beacon positions (design parameter) ---
# Beacons cannot be placed inside the lane region (problem statement).
# We use 3 beacons placed outside the track, distributed around the
# perimeter to avoid poor geometric dilution of precision (GDOP).
# Placement is based on geometric intuition at this stage;
# a quantitative optimisation (e.g., minimising trace of Fisher info matrix)
# is planned as an extension.
beacons = np.array([
    [ 50.0,  50.0],   # outside top straight
    [120.0, -50.0],   # outside bottom-right curve
    [-30.0,   0.0]    # outside left curve
])
nb = len(beacons)

# --- Initial conditions ---
# P_0 reflects prior uncertainty at t=0 (x_{0|-1} notation from lectures)
# Large position uncertainty (100 m^2) since we do not know where on the
# track the vehicle starts. Velocity initialised near 10 m/s as suggested
# by the problem statement.
P0 = np.diag([100.0, 1.0, 25.0, 0.5])
x0_est = np.array([[0.0], [0.0], [10.0], [0.0]])   # initial estimate


# --- Measurement functions ---

def h_func(x, noise):
    """
    Nonlinear measurement function:
      y_i = || p(x) - b_i ||_2 + v_i
    where p(x) is the vehicle position in Cartesian coords derived from
    state x = [s, ell, v_s, v_ell], and b_i is beacon i's position.
    Noise v_i ~ N(0, R_var) (iid across beacons, independent of w_t).
    """
    px, py = state_to_xy(x)
    return np.array([
        np.sqrt((px - beacons[i, 0])**2 + (py - beacons[i, 1])**2) + noise[i]
        for i in range(nb)
    ])


def jacobian_h(x):
    """
    Numerical Jacobian of h with respect to x, evaluated at current estimate.
    This is the H_t matrix in the EKF linearisation:
      h(x) ~= h(x_{t|t-1}) + H_t (x - x_{t|t-1})
    Only s and ell affect the range measurements; v_s and v_ell do not,
    so columns 2 and 3 of H_t are zero.
    Using finite differences (central difference would be more accurate
    but forward difference is sufficient here given small eps).
    """
    eps = 1e-5
    H = np.zeros((nb, 4))
    h0 = h_func(x, np.zeros(nb))
    for j in range(2):   # only differentiate w.r.t. s and ell
        x_pert = x.copy()
        x_pert[j] += eps
        h1 = h_func(x_pert, np.zeros(nb))
        H[:, j] = (h1.flatten() - h0.flatten()) / eps
    return H


# --- EKF: measurement update (x_{t|t-1} -> x_{t|t}) ---
def measurement_update(P_pred, x_pred, y_meas):
    """
    Standard EKF measurement update step.
    Following the notation from ELE8101 lectures (Gauss-Markov / KF slides):

      Innovation:  e_t = y_t - h(x_{t|t-1})
      Innovation covariance: S_t = H_t P_{t|t-1} H_t^T + R_tilde
      Kalman gain: K_t = P_{t|t-1} H_t^T S_t^{-1}
      Updated state: x_{t|t} = x_{t|t-1} + K_t e_t
      Updated covariance: P_{t|t} = P_{t|t-1} - K_t H_t P_{t|t-1}

    Note: we use np.linalg.solve instead of explicit matrix inversion
    for numerical stability.
    """
    H = jacobian_h(x_pred)
    S = H @ P_pred @ H.T + R_var * np.eye(nb)
    innov = y_meas - h_func(x_pred, np.zeros(nb))
    x_upd = x_pred + P_pred @ H.T @ np.linalg.solve(S, innov.reshape(-1, 1))
    P_upd = P_pred - P_pred @ H.T @ np.linalg.solve(S, H @ P_pred)
    return P_upd, x_upd


# --- EKF: time update (x_{t|t} -> x_{t+1|t}) ---
def time_update(P_upd, x_upd):
    """
    EKF prediction step (linear dynamics, so no Jacobian needed for A):
      x_{t+1|t} = A x_{t|t}
      P_{t+1|t} = A P_{t|t} A^T + G Q G^T

    Hard constraint: clip lateral offset to [-2, 2] m after prediction.
    This enforces the track boundary constraint from the problem statement.
    A cleaner approach would be constrained estimation (e.g., MHE), which
    is planned as a follow-up.
    """
    x_pred = A @ x_upd
    x_pred[1] = np.clip(x_pred[1], -2.0, 2.0)   # enforce lane boundary
    P_pred = A @ P_upd @ A.T + G @ Q_mat @ G.T
    return P_pred, x_pred


# =============================================================
# Simulation
# =============================================================
n_steps = 3000   # 30 s at 100 Hz ~ one full lap (L ~ 325 m at ~10 m/s)

x_true = np.array([[0.0], [0.0], [10.0], [0.0]])   # true initial state
x_est  = x0_est.copy()
P_est  = P0.copy()

log_true = np.zeros((n_steps, 4))
log_est  = np.zeros((n_steps - 1, 4))
log_true[0] = x_true.T

t_start = time.time()

for t in range(n_steps - 1):

    # Ground truth: generate noisy beacon measurements
    v_noise = np.random.normal(0, 1.5, nb)          # v_t ~ N(0, 1.5^2) per beacon
    y_t = h_func(x_true, v_noise)

    # EKF measurement update: x_{t|t-1} -> x_{t|t}
    P_est, x_est = measurement_update(P_est, x_est, y_t)
    log_est[t] = x_est.T

    # EKF time update: x_{t|t} -> x_{t+1|t}
    P_est, x_est = time_update(P_est, x_est)

    # Ground truth: propagate true state with process noise w_t ~ N(0, Q)
    w_t = np.array([
        [np.random.normal(0, np.sqrt(Q_mat[0, 0]))],
        [np.random.normal(0, np.sqrt(Q_mat[1, 1]))]
    ])
    x_true = A @ x_true + G @ w_t
    x_true[1] = np.clip(x_true[1], -2.0, 2.0)
    log_true[t + 1] = x_true.T

t_total = time.time() - t_start
t_per_step = t_total / n_steps * 1000   # ms per step

# =============================================================
# Results and plots
# =============================================================
true_xy = np.array([state_to_xy(log_true[t]) for t in range(n_steps)])
est_xy  = np.array([state_to_xy(log_est[t])  for t in range(n_steps - 1)])

s_vals   = np.linspace(0, L, 500)
track_xy = np.array([s_to_xy(s) for s in s_vals])

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
fig.suptitle('EKF — Step 3: Full 2D with lateral dynamics', fontsize=13)

# --- 2D track view ---
axes[0].plot(track_xy[:, 0], track_xy[:, 1], 'k-', lw=8, alpha=0.12, label='Track centreline')
axes[0].plot(true_xy[:, 0], true_xy[:, 1], 'b-',  lw=0.8, label='True trajectory')
axes[0].plot(est_xy[:, 0],  est_xy[:, 1],  'r--', lw=0.8, label='EKF estimate')
for i, b in enumerate(beacons):
    axes[0].plot(b[0], b[1], 'gx', ms=12, mew=3, label=f'Beacon {i+1}' if i == 0 else '')
axes[0].set_aspect('equal')
axes[0].set_xlabel('x (m)')
axes[0].set_ylabel('y (m)')
axes[0].legend(fontsize=8)
axes[0].set_title('Vehicle trajectory')

# --- Lateral offset ---
t_ax = np.arange(n_steps) * h
axes[1].plot(t_ax,      log_true[:, 1], 'b-',  lw=0.9, label=r'True $\ell_t$')
axes[1].plot(t_ax[:-1], log_est[:,  1], 'r--', lw=0.9, label=r'EKF $\hat{\ell}_{t|t}$')
axes[1].axhline( 2.0, color='k', ls=':', lw=1.0, label='Boundary ±2 m')
axes[1].axhline(-2.0, color='k', ls=':', lw=1.0)
axes[1].set_xlabel('Time (s)')
axes[1].set_ylabel('Lateral offset (m)')
axes[1].legend(fontsize=8)
axes[1].set_title('Lateral position')

# --- Longitudinal velocity ---
axes[2].plot(t_ax,      log_true[:, 2], 'b-',  lw=0.9, label=r'True $v_{s,t}$')
axes[2].plot(t_ax[:-1], log_est[:,  2], 'r--', lw=0.9, label=r'EKF $\hat{v}_{s,t|t}$')
axes[2].axhline(25.0, color='orange', ls='--', lw=1.0, label='Max speed (25 m/s)')
axes[2].set_xlabel('Time (s)')
axes[2].set_ylabel('Longitudinal velocity (m/s)')
axes[2].legend(fontsize=8)
axes[2].set_title('Velocity tracking')

plt.tight_layout()
plt.savefig('step3_ekf_results.png', dpi=150)
plt.show()

# --- Performance metrics ---
arc_err  = np.abs(log_true[:-1, 0] - log_est[:, 0])
lat_err  = np.abs(log_true[:-1, 1] - log_est[:, 1])

print("=" * 50)
print("EKF Performance — Step 3")
print("=" * 50)
print(f"Mean arc-length error   : {np.mean(arc_err):.3f} m")
print(f"Max  arc-length error   : {np.max(arc_err):.3f} m")
print(f"Mean lateral error      : {np.mean(lat_err):.3f} m")
print(f"Lateral bounds satisfied: {np.all(np.abs(log_true[:, 1]) <= 2.0)}")
print(f"Avg compute time/step   : {t_per_step:.4f} ms  (budget: {h*1000:.1f} ms)")
print()
print("Assumptions:")
print(f"  Measurement noise std : 1.5 m (given)")
print(f"  Process noise Q_s     : {Q_mat[0,0]} (assumed — needs validation)")
print(f"  Process noise Q_ell   : {Q_mat[1,1]} (assumed — needs validation)")
print(f"  Lateral damping phi   : {phi} (chosen empirically)")
print()
print("Known limitations:")
print("  - Q values not systematically identified")
print("  - Beacon placement not yet optimised")
print("  - Speed upper bound (25 m/s) not enforced as hard constraint")