# -*- coding: utf-8 -*-
"""ekf_step2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfE753QgbqB2w-zWogeUG7vpI1CQ0ENa
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

h = 0.01       # 100 Hz
d = 100.0      # 直道长度
rho = 20.0     # 弯道半径（中心线）

# 赛道总周长
L = 2*d + 2*np.pi*rho

def s_to_xy(s):
    """把弧长s转换成(x,y)坐标"""
    s = s % L  # 循环赛道
    if s < d:
        # 顶部直道：向右
        return s, rho
    elif s < d + np.pi*rho:
        # 右侧半圆：向下
        angle = (s - d) / rho
        return d + rho*np.sin(angle), rho*np.cos(angle)
    elif s < 2*d + np.pi*rho:
        # 底部直道：向左
        return 2*d + np.pi*rho - s, -rho
    else:
        # 左侧半圆：向上
        angle = (s - (2*d + np.pi*rho)) / rho
        return -rho*np.sin(angle), -rho*np.cos(angle)

# 状态方程 [弧长s, 纵向速度vs]
A = np.array([[1, h],
              [0, 1]])
G = np.array([[0], [1]])

Q = 0.5
R = 1.5**2

# 3个beacon位置（在赛道外）
beacons = np.array([
    [50.0,  50.0],
    [120.0, -50.0],
    [-30.0,  0.0]
])
nb = len(beacons)

P0 = np.diag([100.0, 25.0])
x0 = np.array([[0.0], [10.0]])

def h_func(x, noise):
    """测量函数：弧长s → (x,y) → 到每个beacon的距离"""
    s = x[0]
    px, py = s_to_xy(s)
    return np.array([
        np.sqrt((px - beacons[i,0])**2 + (py - beacons[i,1])**2) + noise[i]
        for i in range(nb)
    ])

def jhx_func(x):
    """测量Jacobian：数值微分"""
    eps = 1e-5
    H = np.zeros((nb, 2))
    h0 = h_func(x, np.zeros(nb))
    x_eps = x.copy()
    x_eps[0] += eps
    h1 = h_func(x_eps, np.zeros(nb))
    H[:, 0] = (h1.flatten() - h0.flatten()) / eps
    return H

def measurement_update(sigma_pred, x_pred, y):
    C = jhx_func(x_pred)
    R_mat = R * np.eye(nb)
    S = C @ sigma_pred @ C.T + R_mat
    innovation = y - h_func(x_pred, np.zeros(nb))
    x_meas = x_pred + sigma_pred @ C.T @ np.linalg.solve(S, innovation.reshape(-1,1))
    sigma_meas = sigma_pred - sigma_pred @ C.T @ np.linalg.solve(S, C @ sigma_pred)
    return sigma_meas, x_meas

def time_update(sigma_meas, x_meas):
    x_pred = A @ x_meas
    sigma_pred = A @ sigma_meas @ A.T + Q * (G @ G.T)
    return sigma_pred, x_pred

# 仿真
n_sim = 3000  # 30秒，绕约一圈
x_true = np.array([[0.0], [10.0]])
x_pred = x0.copy()
sigma_pred = P0.copy()

x_true_cache = np.zeros((n_sim, 2))
x_est_cache  = np.zeros((n_sim-1, 2))
x_true_cache[0] = x_true.T

for t in range(n_sim - 1):
    v_noise = np.random.normal(0, 1.5, nb)
    y = h_func(x_true, v_noise)
    sigma_meas, x_meas = measurement_update(sigma_pred, x_pred, y)
    x_est_cache[t] = x_meas.T
    sigma_pred, x_pred = time_update(sigma_meas, x_meas)
    w = np.random.normal(0, np.sqrt(Q))
    x_true = A @ x_true + G * w
    x_true_cache[t+1] = x_true.T

# 转换成(x,y)坐标画图
true_xy  = np.array([s_to_xy(s) for s in x_true_cache[:,0]])
est_xy   = np.array([s_to_xy(s) for s in x_est_cache[:,0]])

# 画赛道轮廓
s_track = np.linspace(0, L, 500)
track_xy = np.array([s_to_xy(s) for s in s_track])

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# 左图：2D轨迹
axes[0].plot(track_xy[:,0], track_xy[:,1], 'k-', linewidth=3, alpha=0.3, label='Track')
axes[0].plot(true_xy[:,0], true_xy[:,1], 'b-', label='True trajectory')
axes[0].plot(est_xy[:,0],  est_xy[:,1],  'r--', label='EKF estimate')
for i, b in enumerate(beacons):
    axes[0].plot(b[0], b[1], 'gx', markersize=12, markeredgewidth=3)
    axes[0].annotate(f'b{i+1}', b, textcoords="offset points", xytext=(5,5))
axes[0].set_aspect('equal')
axes[0].legend()
axes[0].set_title('Step 2: EKF on curved track')

# 右图：速度
t_axis = np.arange(n_sim) * h
axes[1].plot(t_axis, x_true_cache[:,1], 'b-', label='True velocity')
axes[1].plot(t_axis[:-1], x_est_cache[:,1], 'r--', label='EKF estimate')
axes[1].set_ylabel('Velocity (m/s)')
axes[1].set_xlabel('Time (s)')
axes[1].legend()
axes[1].set_title('Velocity tracking')

plt.tight_layout()
plt.show()

# 误差统计
pos_errors = np.abs(x_true_cache[:-1,0] - x_est_cache[:,0])
print(f"平均弧长误差: {np.mean(pos_errors):.3f} m")
print(f"最大弧长误差: {np.max(pos_errors):.3f} m")